version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.43
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4317:4317"
    restart: unless-stopped