spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: task-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/tasks/**
          filters:
            - AddRequestHeader=X-Gateway-Trace, API-Gateway
        - id: another-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/another/**